package dorks

import (
	"github.com/Nerd658/dorkforge/internal/models"
)

var ExpandedCatalog = []models.Dork{
	// ---------------------------------------------------------
	// CLOUD & SAAS (Modern Cloud Reconnaissance)
	// ---------------------------------------------------------
	{
		ID:            "cld-004",
		Title:         "Exposed Firebase Realtime Databases",
		Description:   "Discovers public Firebase Realtime Database instances with insecure read/write permissions.",
		Category:      models.CategoryCloud,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:firebaseio.com \"{{TARGET}}\" | \"{{ORG}}\"",
		Tags:          []string{"firebase", "cloud", "database"},
		Remediation:   "Enforce strict Firebase Security Rules (.read != true) and restrict access using Firebase Authentication.",
	},
	{
		ID:            "cld-005",
		Title:         "Public Google Sheets and Drive Documents",
		Description:   "Searches for public Google Spreadsheets and Drive documents referencing the target organization.",
		Category:      models.CategoryCloud,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:docs.google.com/spreadsheets/d/ \"{{TARGET}}\" | \"{{ORG}}\"",
		Tags:          []string{"google-sheets", "drive", "documents"},
		Remediation:   "Audit Google Workspace sharing permissions and enforce domain-only sharing for sensitive sheets.",
	},
	{
		ID:            "cld-006",
		Title:         "Jira and Confluence Public Atlassian Cloud Instances",
		Description:   "Identifies Atlassian Cloud subdomains (atlassian.net) associated with the target exposing open ticket trackers.",
		Category:      models.CategoryCloud,
		Severity:      models.SeverityMedium,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:atlassian.net \"{{TARGET}}\" | \"{{ORG}}\"",
		Tags:          []string{"jira", "confluence", "atlassian"},
		Remediation:   "Configure Atlassian Cloud permissions to require authenticated login for all project spaces.",
	},
	{
		ID:            "cld-007",
		Title:         "Salesforce Communities and Force.com Endpoints",
		Description:   "Discovers Salesforce Experience Cloud communities and Force.com sites that may expose guest user records.",
		Category:      models.CategoryCloud,
		Severity:      models.SeverityMedium,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:force.com \"{{TARGET}}\" | \"{{ORG}}\"",
		Tags:          []string{"salesforce", "crm", "cloud"},
		Remediation:   "Audit Salesforce Guest User Profile permissions and secure Aura/Lightning controller access.",
	},
	{
		ID:            "cld-008",
		Title:         "Public Notion Workspaces and Knowledge Bases",
		Description:   "Locates publicly shared Notion workspace pages containing internal standard operating procedures.",
		Category:      models.CategoryCloud,
		Severity:      models.SeverityMedium,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:notion.site \"{{TARGET}}\" | site:notion.so \"{{TARGET}}\"",
		Tags:          []string{"notion", "knowledge-base", "docs"},
		Remediation:   "Review public share settings on Notion team workspaces and disable 'Share to Web' on internal pages.",
	},
	{
		ID:            "cld-009",
		Title:         "Public Airtable Bases and Shared Views",
		Description:   "Finds shared Airtable bases (airtable.com/shr) exposing client lists or internal trackers.",
		Category:      models.CategoryCloud,
		Severity:      models.SeverityMedium,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:airtable.com/shr \"{{TARGET}}\" | \"{{ORG}}\"",
		Tags:          []string{"airtable", "database", "saas"},
		Remediation:   "Audit Airtable shared view links and enforce password protection.",
	},
	{
		ID:            "cld-010",
		Title:         "Exposed AWS S3 Bucket XML Directory Listings",
		Description:   "Detects open S3 buckets returning public ListBucketResult XML directories exposing file paths.",
		Category:      models.CategoryCloud,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:s3.amazonaws.com intext:\"ListBucketResult\" \"{{TARGET}}\" | \"{{ORG}}\"",
		Tags:          []string{"aws", "s3", "storage"},
		Remediation:   "Enable 'Block public access' and remove s3:ListBucket permissions for anonymous users.",
	},

	// ---------------------------------------------------------
	// MODERN DEV & FRAMEWORKS
	// ---------------------------------------------------------
	{
		ID:            "cfg-005",
		Title:         "Next.js and Nuxt Environment Files",
		Description:   "Detects exposed .env.local or .env.production files in modern JavaScript/TypeScript framework deployments.",
		Category:      models.CategoryConfigs,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (inurl:.env.local | inurl:.env.production | inurl:.env.development | filename:.env.local)",
		Tags:          []string{"nextjs", "nuxt", "frontend", "env"},
		Remediation:   "Configure web server and CDN edge policies to block access to all dotfiles.",
	},
	{
		ID:            "cfg-006",
		Title:         "Terraform State and Variables Files",
		Description:   "Discovers unencrypted terraform.tfstate and terraform.tfvars files containing plaintext cloud infrastructure secrets.",
		Category:      models.CategoryConfigs,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (filename:terraform.tfstate | filename:terraform.tfvars | ext:tfstate | ext:tfvars)",
		Tags:          []string{"terraform", "iac", "cloud"},
		Remediation:   "Migrate Terraform state to encrypted remote backends with restricted IAM access.",
	},
	{
		ID:            "cfg-007",
		Title:         "Prisma ORM Database Schema Definitions",
		Description:   "Finds schema.prisma definitions exposing complete database schema models and connection strings.",
		Category:      models.CategoryConfigs,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (filename:schema.prisma | inurl:prisma/schema.prisma)",
		Tags:          []string{"prisma", "orm", "database"},
		Remediation:   "Exclude the prisma directory and schema definitions from production build outputs.",
	},
	{
		ID:            "cfg-008",
		Title:         "Spring Boot Actuator Environment Endpoint",
		Description:   "Identifies unauthenticated /actuator/env endpoints exposing active environment variables and properties.",
		Category:      models.CategoryConfigs,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (inurl:/actuator/env | inurl:/actuator/configprops | inurl:/env)",
		Tags:          []string{"springboot", "actuator", "java"},
		Remediation:   "Disable sensitive Actuator endpoints in application properties via management.endpoints.web.exposure.exclude=env.",
	},
	{
		ID:            "cfg-009",
		Title:         "Kubernetes Manifests and Helm Values Files",
		Description:   "Discovers exposed Kubernetes deployment YAMLs and Helm values.yaml containing internal service configurations.",
		Category:      models.CategoryConfigs,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (filename:values.yaml | filename:deployment.yaml | filename:k8s.yaml)",
		Tags:          []string{"kubernetes", "helm", "devops"},
		Remediation:   "Prevent deployment pipelines from publishing Kubernetes manifests to public web server paths.",
	},
	{
		ID:            "cfg-010",
		Title:         "Directory Indexing and Sensitive Footholds (Index of /)",
		Description:   "Detects enabled directory listings (Index of /) leaking directory structures and unlinked files.",
		Category:      models.CategoryConfigs,
		Severity:      models.SeverityMedium,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} intitle:\"Index of /\" (\"Parent Directory\" | \"Name\" | \"Last modified\")",
		Tags:          []string{"directory-listing", "ghdb", "foothold"},
		Remediation:   "Disable directory browsing in web server configuration (Options -Indexes in Apache, autoindex off in Nginx).",
	},

	// ---------------------------------------------------------
	// CREDENTIALS & API TOKENS (GHDB + Modern APIs)
	// ---------------------------------------------------------
	{
		ID:            "sec-005",
		Title:         "OpenAI and LLM API Key Leaks",
		Description:   "Searches GitHub code search for exposed OpenAI API keys associated with the target domain.",
		Category:      models.CategorySecrets,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGitHub,
		QueryTemplate: "\"{{TARGET}}\" AND (\"sk-proj-\" OR \"sk-live-\" OR \"OPENAI_API_KEY\")",
		Tags:          []string{"openai", "ai", "llm", "tokens"},
		Remediation:   "Revoke exposed OpenAI API keys immediately in the OpenAI platform dashboard.",
	},
	{
		ID:            "sec-006",
		Title:         "Exposed Slack Incoming Webhook URLs",
		Description:   "Discovers leaked Slack incoming webhook endpoints allowing arbitrary channel message posting.",
		Category:      models.CategorySecrets,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (\"hooks.slack.com/services/T\" | \"hooks.slack.com/workflows/\")",
		Tags:          []string{"slack", "webhook", "chatops"},
		Remediation:   "Delete compromised Slack incoming webhooks in Slack App management and generate new ones.",
	},
	{
		ID:            "sec-007",
		Title:         "Stripe Live Secret and Restricted API Keys",
		Description:   "Searches GitHub for live production Stripe secret keys and webhook signing secrets.",
		Category:      models.CategorySecrets,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGitHub,
		QueryTemplate: "\"{{TARGET}}\" AND (\"sk_live_\" OR \"rk_live_\" OR \"whsec_\")",
		Tags:          []string{"stripe", "payments", "financial"},
		Remediation:   "Roll the compromised Stripe secret keys in the Stripe Developer Dashboard.",
	},
	{
		ID:            "sec-008",
		Title:         "SendGrid and Mailgun API Tokens",
		Description:   "Finds exposed SendGrid (SG.) and Mailgun email delivery API credentials in source repositories.",
		Category:      models.CategorySecrets,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGitHub,
		QueryTemplate: "\"{{TARGET}}\" AND (\"SG.\" \"sendgrid\" OR \"key-\" \"mailgun\")",
		Tags:          []string{"sendgrid", "mailgun", "email"},
		Remediation:   "Rotate email service provider API keys to prevent domain reputation damage.",
	},
	{
		ID:            "sec-009",
		Title:         "Twilio Account SID and Auth Tokens",
		Description:   "Identifies leaked Twilio Account SID and Auth Token combinations enabling SMS and voice toll fraud.",
		Category:      models.CategorySecrets,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGitHub,
		QueryTemplate: "\"{{TARGET}}\" AND (\"AC\" \"twilio\" AND (\"TWILIO_AUTH_TOKEN\" OR \"authToken\"))",
		Tags:          []string{"twilio", "telephony", "sms"},
		Remediation:   "Regenerate Twilio Auth Tokens in Twilio Console.",
	},
	{
		ID:            "sec-010",
		Title:         "Exposed Google Cloud and Maps API Keys",
		Description:   "Detects unconstrained Google Cloud API keys in client-side scripts and markup.",
		Category:      models.CategorySecrets,
		Severity:      models.SeverityMedium,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (\"AIzaSy\" | \"maps.googleapis.com/maps/api/js?key=AIza\")",
		Tags:          []string{"google-cloud", "gcp", "maps"},
		Remediation:   "Apply HTTP referrer and API service restrictions to Google Cloud API keys.",
	},
	{
		ID:            "sec-011",
		Title:         "Anthropic Claude and Hugging Face API Tokens",
		Description:   "Locates exposed Anthropic Claude and Hugging Face inference API access tokens.",
		Category:      models.CategorySecrets,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGitHub,
		QueryTemplate: "\"{{TARGET}}\" AND (\"sk-ant-api03-\" OR \"hf_\" \"huggingface\")",
		Tags:          []string{"anthropic", "huggingface", "ai"},
		Remediation:   "Revoke exposed AI platform tokens and use managed secrets stores.",
	},
	{
		ID:            "sec-012",
		Title:         "Exposed htpasswd and Apache Auth Files",
		Description:   "Discovers exposed .htpasswd and .htaccess password hashes stored in public directories.",
		Category:      models.CategorySecrets,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (filename:.htpasswd | filename:.htgroup | ext:htpasswd)",
		Tags:          []string{"htpasswd", "passwords", "apache", "ghdb"},
		Remediation:   "Store .htpasswd files strictly outside the public web tree and deny serving dotfiles.",
	},

	// ---------------------------------------------------------
	// CI/CD & CONTAINERS (DevSecOps)
	// ---------------------------------------------------------
	{
		ID:            "adm-004",
		Title:         "ArgoCD GitOps Continuous Delivery Dashboards",
		Description:   "Finds publicly reachable ArgoCD web management interfaces providing control over Kubernetes cluster deployments.",
		Category:      models.CategoryAdmin,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (intitle:\"Argo CD\" | inurl:argocd | inurl:argo-cd)",
		Tags:          []string{"argocd", "gitops", "kubernetes", "cicd"},
		Remediation:   "Enforce SSO/OIDC authentication with MFA and place ArgoCD UI behind an internal VPN.",
	},
	{
		ID:            "adm-005",
		Title:         "Kubernetes Web Dashboard Consoles",
		Description:   "Discovers exposed Kubernetes Web Dashboard instances that may allow cluster-wide pod and secret management.",
		Category:      models.CategoryAdmin,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (intitle:\"Kubernetes Dashboard\" | inurl:\"/api/v1/namespaces/kubernetes-dashboard\")",
		Tags:          []string{"kubernetes", "k8s", "dashboard"},
		Remediation:   "Disable external public ingress for Kubernetes Dashboard and access strictly via kubectl proxy.",
	},
	{
		ID:            "adm-006",
		Title:         "SonarQube Code Quality Dashboards",
		Description:   "Identifies unauthenticated SonarQube instances exposing project source code analysis and vulnerability findings.",
		Category:      models.CategoryAdmin,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (intitle:\"SonarQube\" | inurl:\"/sonar/dashboard\" | inurl:\"/sonarqube\")",
		Tags:          []string{"sonarqube", "code-quality", "devops"},
		Remediation:   "Enable 'Force user authentication' in SonarQube Global Settings.",
	},
	{
		ID:            "adm-007",
		Title:         "Message Broker and Cache Management Consoles",
		Description:   "Detects exposed RabbitMQ Management, Redis Commander, or Kafka UI consoles.",
		Category:      models.CategoryAdmin,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (intitle:\"RabbitMQ Management\" | intitle:\"Redis Commander\" | intitle:\"Kafka UI\")",
		Tags:          []string{"rabbitmq", "redis", "kafka"},
		Remediation:   "Restrict message broker management ports to internal private networks.",
	},
	{
		ID:            "adm-008",
		Title:         "Traefik and Reverse Proxy Dashboards",
		Description:   "Finds exposed Traefik management dashboards revealing backend routing rules and internal hosts.",
		Category:      models.CategoryAdmin,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (intitle:\"Traefik\" inurl:dashboard | inurl:\"/api/rawdata\")",
		Tags:          []string{"traefik", "reverse-proxy", "routing"},
		Remediation:   "Configure authentication middleware on Traefik API/dashboard entrypoints.",
	},

	// ---------------------------------------------------------
	// DATABASE, SOURCE & LOGS
	// ---------------------------------------------------------
	{
		ID:            "bak-003",
		Title:         "SQLite Database Files",
		Description:   "Locates raw SQLite database files (.sqlite, .sqlite3, .db) containing full application data.",
		Category:      models.CategoryBackups,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (ext:sqlite | ext:sqlite3 | ext:db3 | ext:db) (\"SQLite format 3\")",
		Tags:          []string{"sqlite", "database"},
		Remediation:   "Store embedded databases outside public document roots.",
	},
	{
		ID:            "bak-004",
		Title:         "Spring Boot Heap and Memory Dump Files",
		Description:   "Detects accessible /actuator/heapdump and JVM heap dumps containing in-memory plaintext passwords.",
		Category:      models.CategoryBackups,
		Severity:      models.SeverityCritical,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (inurl:/actuator/heapdump | inurl:/heapdump | inurl:/actuator/threaddump)",
		Tags:          []string{"springboot", "heapdump", "memory"},
		Remediation:   "Explicitly disable heapdump and threaddump actuator endpoints in production.",
	},
	{
		ID:            "src-003",
		Title:         "Exposed SVN and Mercurial Version Control Metadata",
		Description:   "Detects exposed Subversion (.svn) or Mercurial (.hg) repositories allowing source code recovery.",
		Category:      models.CategorySourceCode,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (inurl:/.svn/entries | inurl:/.svn/wc.db | inurl:/.hg/store)",
		Tags:          []string{"svn", "mercurial", "vcs"},
		Remediation:   "Block HTTP access to .svn and .hg directories in web server configuration.",
	},
	{
		ID:            "src-004",
		Title:         "GitLab CI/CD Configurations and Runner Tokens",
		Description:   "Searches GitHub for target domain references inside .gitlab-ci.yml pipeline files and runner configurations.",
		Category:      models.CategorySourceCode,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGitHub,
		QueryTemplate: "\"{{TARGET}}\" (filename:.gitlab-ci.yml OR filename:config.toml \"runners\")",
		Tags:          []string{"gitlab", "cicd", "runners"},
		Remediation:   "Use CI/CD masked variables for sensitive runner tokens.",
	},
	{
		ID:            "src-005",
		Title:         "JavaScript and TypeScript Source Maps",
		Description:   "Discovers deployed .js.map and .ts.map source maps that allow reconstruction of original unminified front-end source code.",
		Category:      models.CategorySourceCode,
		Severity:      models.SeverityMedium,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (ext:map \"sourcesContent\" | inurl:.js.map | inurl:.ts.map)",
		Tags:          []string{"sourcemap", "javascript", "frontend"},
		Remediation:   "Disable production source map generation or restrict source map access to authenticated error monitoring tools.",
	},
	{
		ID:            "err-004",
		Title:         "Apache and Nginx Server Status Pages",
		Description:   "Exploit-DB classic dork finding exposed /server-status or /server-info diagnostic consoles.",
		Category:      models.CategoryErrors,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (inurl:\"/server-status\" | inurl:\"/server-info\") (\"Apache Status\" | \"Current Time\")",
		Tags:          []string{"apache", "server-status", "ghdb"},
		Remediation:   "Restrict mod_status to localhost / internal management networks.",
	},
	{
		ID:            "err-005",
		Title:         "SQL Syntax Error and Database Disclosures",
		Description:   "Detects database error disclosures such as unhandled MySQL, PostgreSQL, or Oracle exception traces.",
		Category:      models.CategoryErrors,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (\"SQL syntax\" | \"ORA-\" | \"PostgreSQL query failed\")",
		Tags:          []string{"sql", "database", "errors", "ghdb"},
		Remediation:   "Sanitize all database error outputs and disable verbose database debugging in production APIs.",
	},
	{
		ID:            "doc-003",
		Title:         "Invoices and Purchase Orders",
		Description:   "Discovers public billing, invoice, and purchase order PDF records.",
		Category:      models.CategoryDocs,
		Severity:      models.SeverityMedium,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} ext:pdf (\"invoice\" | \"purchase order\" | \"bill to:\" | \"tax invoice\")",
		Tags:          []string{"invoices", "accounting", "docs"},
		Remediation:   "Place client billing and invoice documents behind authenticated customer portals.",
	},
	{
		ID:            "net-003",
		Title:         "IP Cameras and Network Surveillance",
		Description:   "Exploit-DB classic dork finding online IP camera streams or management consoles.",
		Category:      models.CategoryNetworkIoT,
		Severity:      models.SeverityHigh,
		Engine:        models.EngineGoogle,
		QueryTemplate: "site:{{TARGET}} (inurl:\"view/index.shtml\" | intitle:\"Network Camera\" | intitle:\"Live View / - AXIS\")",
		Tags:          []string{"cctv", "camera", "iot", "ghdb"},
		Remediation:   "Isolate surveillance and IoT devices in restricted IoT VLANs with no default internet exposure.",
	},
}

func init() {
	DefaultCatalog = append(DefaultCatalog, ExpandedCatalog...)
}
